services:
  - type: web
    name: srebrna-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn srebrna_backend.wsgi:application
